Trait {
	#name : 'TZealDefinition',
	#category : 'Zeal',
	#package : 'Zeal'
}

{ #category : 'accessing' }
TZealDefinition >> body [ ^ nil
]

{ #category : 'accessing' }
TZealDefinition >> definitionKind [ ^ #unknown
]

{ #category : 'accessing' }
TZealDefinition >> definitions [ ^ nil
]

{ #category : 'accessing' }
TZealDefinition >> effects [ ^ nil
]

{ #category : 'accessing' }
TZealDefinition >> fields [ ^ nil
]

{ #category : 'accessing' }
TZealDefinition >> interfaces [ ^ nil
]

{ #category : 'testing' }
TZealDefinition >> isEnum [ ^ false
]

{ #category : 'testing' }
TZealDefinition >> isFunction [ ^ false
]

{ #category : 'testing' }
TZealDefinition >> isInterface [ ^ false
]

{ #category : 'testing' }
TZealDefinition >> isModule [ ^ false
]

{ #category : 'accessing' }
TZealDefinition >> isMutable [ ^ nil
]

{ #category : 'testing' }
TZealDefinition >> isNamespace [ ^ false
]

{ #category : 'testing' }
TZealDefinition >> isStruct [ ^ false
]

{ #category : 'testing' }
TZealDefinition >> isVariable [ ^ false
]

{ #category : 'testing' }
TZealDefinition >> isVerseClass [ ^ false
]

{ #category : 'accessing' }
TZealDefinition >> methods [ ^ nil
]

{ #category : 'accessing' }
TZealDefinition >> parameters [ ^ nil
]

{ #category : 'accessing' }
TZealDefinition >> parents [ ^ nil
]

{ #category : 'accessing' }
TZealDefinition >> superclassName [ ^ nil
]

{ #category : 'accessing' }
TZealDefinition >> usings [ ^ nil
]

{ #category : 'accessing' }
TZealDefinition >> value [ ^ nil
]

{ #category : 'accessing' }
TZealDefinition >> values [ ^ nil
]
